version: 2
jobs:
  build:    
    macos:  # indicate that we are using the macOS executor
      xcode: "10.0.0"
    #docker:
     # - image: cirrusci/flutter:v1.5.8 

    branches:
      only: master

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build ios --no-code-sign 

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk

